# Generated by Django 3.2.7 on 2021-10-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'micro-ordinateur', 'verbose_name_plural': 'Processing Units'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Guest', 'verbose_name_plural': 'Guests'},
        ),
        migrations.AlterModelOptions(
            name='guest_processus',
            options={'verbose_name': 'Guest Processus', 'verbose_name_plural': 'Guest_Processus'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': 'Hôte', 'verbose_name_plural': 'Hotes'},
        ),
        migrations.AlterModelOptions(
            name='host_network',
            options={'verbose_name': 'adresse réseau', 'verbose_name_plural': 'Adresses réseau'},
        ),
        migrations.AlterModelOptions(
            name='io',
            options={'verbose_name': 'Signal IO', 'verbose_name_plural': 'Signaux (IO)'},
        ),
        migrations.AlterModelOptions(
            name='log_type',
            options={'verbose_name': 'Type Log', 'verbose_name_plural': 'Log Type'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Réseau', 'verbose_name_plural': 'Networks'},
        ),
        migrations.AlterModelOptions(
            name='networkcard',
            options={'verbose_name': 'Carte réseau', 'verbose_name_plural': 'Cartes réseau'},
        ),
        migrations.AlterModelOptions(
            name='os',
            options={'verbose_name': 'OS', 'verbose_name_plural': 'Operating System'},
        ),
        migrations.AlterModelOptions(
            name='processus',
            options={'verbose_name': 'Processus', 'verbose_name_plural': 'Processus'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': 'Logiciel', 'verbose_name_plural': 'Softwares'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name': 'System', 'verbose_name_plural': 'Systems'},
        ),
        migrations.AlterField(
            model_name='controller',
            name='board',
            field=models.CharField(choices=[('uno', 'Arduino uno'), ('nano', 'Arduino nano'), ('uno_gen', 'Generic uno'), ('nano_gen', 'Generic nano'), ("{'index': 2}", 'Admin Site Details')], default='nano', max_length=16),
        ),
        migrations.AlterField(
            model_name='controller',
            name='desi',
            field=models.CharField(max_length=16, unique=True, verbose_name='desigation'),
        ),
        migrations.AlterField(
            model_name='io',
            name='desi',
            field=models.CharField(max_length=254, verbose_name='designation'),
        ),
        migrations.AlterField(
            model_name='io',
            name='put',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('not', 'Not')], default='in', max_length=16, verbose_name='signal'),
        ),
        migrations.AlterField(
            model_name='io',
            name='type',
            field=models.CharField(choices=[('digital', 'Digital'), ('analog', 'Analog'), ('not', 'Not')], default='digital', max_length=16, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='network',
            name='desi',
            field=models.CharField(max_length=16, verbose_name='designation'),
        ),
        migrations.AlterField(
            model_name='network',
            name='type',
            field=models.CharField(choices=[('eth', 'réseau ethernet'), ('wlan', 'wifi')], default='eth', max_length=4, verbose_name='type'),
        ),
    ]
