# Generated by Django 3.2.6 on 2021-09-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Role équipement',
                'verbose_name_plural': 'Roles équipement',
                'db_table': 'TAB_EQUIPMENT_ROLES',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desi', models.CharField(max_length=16, unique=True, verbose_name='désignation')),
                ('desc', models.CharField(default='', max_length=2000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
                'db_table': 'TAB_FUNCTIONS',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desi', models.CharField(max_length=16, unique=True, verbose_name='désignation')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='description')),
                ('group_des', models.CharField(max_length=16, null=True, verbose_name='désignation group')),
            ],
            options={
                'verbose_name': 'Procédé',
                'verbose_name_plural': 'Procédés',
                'db_table': 'TAB_PROCESS',
            },
        ),
        migrations.CreateModel(
            name='ProdLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desi', models.CharField(max_length=16, unique=True)),
                ('desc', models.CharField(default='', max_length=200)),
                ('statut', models.IntegerField(choices=[(2, 'En fonctionnement'), (3, 'En Production'), (0, 'Fermée'), (20, 'En maintenance'), (1, 'Arrêtée'), (10, 'En attente')], default=20)),
                ('cur_speed', models.IntegerField(default=0)),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wshop.process')),
            ],
            options={
                'verbose_name': 'Ligne de production',
                'verbose_name_plural': '1------------Production Lines',
                'db_table': 'TAB_PRODLINES',
            },
        ),
        migrations.CreateModel(
            name='Specif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desi', models.CharField(max_length=16, unique=True, verbose_name='désignation')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='description')),
                ('typespecif', models.CharField(choices=[('nan', 'Indéfini'), ('pos', 'Position'), ('mes', 'Mesure'), ('press', 'Pression'), ('freq', 'Fréquence')], default='nan', max_length=16)),
                ('unit', models.CharField(choices=[('none', 'Sans'), ('mm', 'millimètres'), ('m', 'mètre'), ('bar', 'bar'), ('hz', 'Hz')], default='none', max_length=16)),
            ],
            options={
                'db_table': 'TAB_SPECIFS',
            },
        ),
        migrations.CreateModel(
            name='WShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desi', models.CharField(max_length=16, unique=True, verbose_name='désignation')),
                ('desc', models.CharField(default='', max_length=2000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Atelier',
                'verbose_name_plural': '0------------Workshops',
                'db_table': 'TAB_WSHOPS',
            },
        ),
        migrations.CreateModel(
            name='Specific_Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('specif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wshop.specif')),
            ],
            options={
                'db_table': 'TAB_SPECIFIC_VALUES',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desi', models.CharField(max_length=16, unique=True, verbose_name='désignation')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='description')),
                ('relates_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wshop.service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'TAB_SERVICES',
            },
        ),
        migrations.CreateModel(
            name='ProdlineStatus_Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[(2, 'En fonctionnement'), (3, 'En Production'), (0, 'Fermée'), (20, 'En maintenance'), (1, 'Arrêtée'), (10, 'En attente')], default=1, max_length=16)),
                ('new_status', models.CharField(choices=[(2, 'En fonctionnement'), (3, 'En Production'), (0, 'Fermée'), (20, 'En maintenance'), (1, 'Arrêtée'), (10, 'En attente')], default=2, max_length=16)),
                ('recorded_at', models.DateTimeField(verbose_name='enregistrement')),
                ('prodline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wshop.prodline')),
            ],
            options={
                'db_table': 'TAB_PRODLINESTATUS_CHANGES',
            },
        ),
        migrations.CreateModel(
            name='ProdLine_Specific_Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wshop.prodline')),
                ('specif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wshop.specific_value')),
            ],
            options={
                'db_table': 'TAB_PRODLINE_SPECIFIC_VALUES',
            },
        ),
        migrations.AddField(
            model_name='prodline',
            name='specifs',
            field=models.ManyToManyField(through='wshop.ProdLine_Specific_Values', to='wshop.Specific_Value'),
        ),
        migrations.AddField(
            model_name='prodline',
            name='wshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wshop.wshop'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wshop.function')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wshop.service')),
            ],
            options={
                'verbose_name': 'poste',
                'verbose_name_plural': 'postes',
                'db_table': 'TAB_JOBS',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, null=True)),
                ('manufact', models.CharField(max_length=200, null=True)),
                ('detail', models.CharField(max_length=2000, null=True)),
                ('condition', models.CharField(choices=[('Undefined', 'Undefined'), ('Fully Functional', 'Fully Functional'), ('Full Overhaul', 'Full Overhaul'), ('As New', 'As New'), ('Minor Repair', 'Minor Repair'), ('Scrap/Spares Only', 'Scrap/Spares Only')], default='Undefined', max_length=32)),
                ('status', models.CharField(choices=[('Undefined', 'Undefined'), ('Surplus', 'Surplus'), ('Standalone', 'Standalone'), ('Operational', 'Operational')], default='Undefined', max_length=32)),
                ('equitype', models.CharField(choices=[('Undefined', 'Undefined'), ('1', 'Ligne de production'), ('4', 'Qualité')], default='Undefined', max_length=32)),
                ('running', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wshop.service')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wshop.process')),
                ('prodline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wshop.prodline')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wshop.equipment_role')),
                ('wshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wshop.wshop')),
            ],
            options={
                'verbose_name': 'Equipement',
                'verbose_name_plural': '2------------Equipments',
                'db_table': 'TAB_EQUIPMENTS',
            },
        ),
        migrations.CreateModel(
            name='Collab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgm', models.CharField(max_length=5, unique=True, verbose_name='Trigramme')),
                ('name', models.CharField(max_length=200, verbose_name='NOM Prénom')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('activ', models.BooleanField(default=True, verbose_name='Actif')),
                ('start_at', models.DateField(verbose_name='début')),
                ('end_at', models.DateField(null=True, verbose_name='Fin')),
                ('contract', models.CharField(choices=[('nan', 'Indéfini'), ('cdi', 'Contrat à durée indéterminée'), ('cdd', 'Contrat à durée déterminée'), ('app', 'Apprentissage'), ('int', 'Interim'), ('presta', 'Prestation')], default='nan', max_length=16, verbose_name='Contrat')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wshop.job')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wshop.collab')),
            ],
            options={
                'verbose_name': 'Collaborateur',
                'verbose_name_plural': 'Collaborateurs',
                'db_table': 'TAB_COLLABS',
            },
        ),
        migrations.AddConstraint(
            model_name='specific_value',
            constraint=models.UniqueConstraint(fields=('specif', 'value'), name='unique specific value'),
        ),
    ]
